services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  backend:
    build: .
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    volumes:
      - .:/app
    command: celery -A celery_worker.celery_app worker --loglevel=info
    depends_on:
      - redis
